version: "3.8"

services:
    computacion:
            container_name: container-computacion
            restart: always
            build: .
            ports:
                - "8080:4000"
            links:
                - mysql    
            volumes:
                 - .:/app   
                 - '/app/node_modules'

    mysql:
            container_name: mysql-db
            image: mysql:5.7.25
            command: --default-authentication-plugin=mysql_native_password
            restart: always
            volumes:
                 - ./sql-data/db:/var/lib/mysql
            ports:
                - "3307:3306"
            hostname: prueba
            environment:    
              MYSQL_DATABASE: "template-computacion" 
              MYSQL_USER: 'root'
              MYSQL_PASSWORD: 'root'
              MYSQL_ROOT_PASSWORD: 'root'



            


  

                 


